Select * from Manufacturer

Insert into Manufacturer (ManufacturerName) values ('Audi')
Insert into Manufacturer (ManufacturerName) values ('Bentley')
Insert into Manufacturer (ManufacturerName) values ('BMW')
Insert into Manufacturer (ManufacturerName) values ('Chevrolet')
Insert into Manufacturer (ManufacturerName) values ('Datsun')
Insert into Manufacturer (ManufacturerName) values ('DC')
Insert into Manufacturer (ManufacturerName) values ('Fiat')
Insert into Manufacturer (ManufacturerName) values ('Ford')
Insert into Manufacturer (ManufacturerName) values ('Hindustan')
Insert into Manufacturer (ManufacturerName) values ('Honda')
Insert into Manufacturer (ManufacturerName) values ('Hyundai')
Insert into Manufacturer (ManufacturerName) values ('Isuzu')
Insert into Manufacturer (ManufacturerName) values ('Jaguar')
Insert into Manufacturer (ManufacturerName) values ('Jeep')
Insert into Manufacturer (ManufacturerName) values ('Kia')

Insert into Manufacturer (ManufacturerName) values ('Land Rover')
Insert into Manufacturer (ManufacturerName) values ('Lexus')
Insert into Manufacturer (ManufacturerName) values ('Mahindra')
Insert into Manufacturer (ManufacturerName) values ('Maruti Suzuki')
Insert into Manufacturer (ManufacturerName) values ('Mercedes-Benz')

Insert into Manufacturer (ManufacturerName) values ('MG')
Insert into Manufacturer (ManufacturerName) values ('MINI')
Insert into Manufacturer (ManufacturerName) values ('Mitsubishi')
Insert into Manufacturer (ManufacturerName) values ('Nissan')
Insert into Manufacturer (ManufacturerName) values ('Porsche')

Insert into Manufacturer (ManufacturerName) values ('Premier')
Insert into Manufacturer (ManufacturerName) values ('Renault')
Insert into Manufacturer (ManufacturerName) values ('Skoda')
Insert into Manufacturer (ManufacturerName) values ('Ssangyong')
Insert into Manufacturer (ManufacturerName) values ('Tata')

Insert into Manufacturer (ManufacturerName) values ('Toyota')
Insert into Manufacturer (ManufacturerName) values ('Volkswagen')
Insert into Manufacturer (ManufacturerName) values ('Volvo')